# Generated by Django 5.1.4 on 2025-01-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicTasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='Default description text'),
        ),
        migrations.AddField(
            model_name='task',
            name='downloadable_resources',
            field=models.FileField(blank=True, null=True, upload_to='activities/resources/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/images/'),
        ),
    ]
