# Generated by Django 5.1.4 on 2025-01-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicTasks', '0002_task_description_task_downloadable_resources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='links',
            field=models.TextField(default='links'),
        ),
    ]
