# Generated by Django 5.1.4 on 2025-01-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicTasks', '0003_task_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='Default description text', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='links',
            field=models.TextField(default='links', null=True),
        ),
    ]
