# Generated by Django 5.1.4 on 2025-01-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicTasks', '0004_alter_task_description_alter_task_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='Default description text', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='links',
            field=models.TextField(blank=True, default='links', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
