# Generated by Django 5.1.4 on 2025-01-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicTasks', '0005_alter_task_description_alter_task_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
