# Generated by Django 5.1.4 on 2025-01-15 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addTasks', '0001_initial'),
        ('topicTasks', '0006_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='addTasks.addtask'),
        ),
    ]
