# Generated by Django 5.1.4 on 2025-01-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicTasks', '0007_task_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
