# Generated by Django 5.1.4 on 2025-01-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicTasks', '0009_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='activities/videos/'),
        ),
    ]
