# Generated by Django 5.1.4 on 2024-12-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0002_rename_school_customuser_school_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
