# Generated by Django 5.1.4 on 2024-12-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
