# Generated by Django 5.1.4 on 2025-01-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_school_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
