# Generated by Django 5.1.4 on 2025-01-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0006_remove_customuser_is_school_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_school_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
