# Generated by Django 5.1.4 on 2025-01-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0007_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
    ]
