# Generated by Django 5.1.4 on 2025-01-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0007_customuser_is_school_admin_customuser_is_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('can_add_teacher', 'Can add teacher'), ('can_change_teacher', 'Can change teacher')]},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='location',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
