# Generated by Django 5.1.4 on 2025-01-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0008_alter_teacher_options_remove_teacher_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('can_add_teacher', 'Can add a teacher'), ('can_change_teacher', 'Can change a teacher'), ('can_view_teacher', 'Can view a teacher')]},
        ),
    ]
