# Generated by Django 5.1.4 on 2025-01-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0009_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
    ]
