# Generated by Django 5.1.4 on 2025-01-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0010_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
