# Generated by Django 5.1.4 on 2025-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0011_teacher_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
