# Generated by Django 5.1.4 on 2025-01-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachment', models.FileField(upload_to='how_it_works_attachments/')),
                ('image', models.ImageField(upload_to='how_it_works_images/')),
            ],
        ),
    ]
