# Generated by Django 5.1.4 on 2025-01-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ENGINEER ROLE MODEL', 'Engineer Role Model'), ('STORY', 'Story'), ('EXPLAINER', 'Explainer'), ('ACTIVITY 1', 'Activity 1'), ('ACTIVITY 2', 'Activity 2'), ('ACTIVITY 3 ', 'Activity 3'), ('JUNK MODELLING', 'Junk Modelling'), ('PHYSICAL ACTIVITIES', 'Physical Activities'), ('PLAY PROVOCATIONS', 'Play Provocations'), ('WORKSHEETS', 'Worksheets'), ('GAMES', 'Games'), ('EXTENSIONS', 'Extensions')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
