# Generated by Django 5.1.4 on 2024-12-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('JUNK_MODEL', 'Junk Modelling'), ('PHYSICAL', 'Physical Activities'), ('PLAY_PROVOCATION', 'Play Provocations'), ('WORKSHEETS', 'Worksheets & Games'), ('EXTENSIONS', 'Extensions'), ('TEACHER_OVERVIEW', 'Teacher Overview'), ('ENGINEER ROLE MODEL', 'Engineer Role Model'), ('TEACHER_OVERVIEW', 'Teacher Overview'), ('STORY', 'Story')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('preparation_time', models.PositiveIntegerField(blank=True, help_text='Time in minutes', null=True)),
                ('downloadable_resources', models.FileField(blank=True, null=True, upload_to='activities/resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
