# Generated by Django 5.1.4 on 2025-01-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_preparation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('INTRODUCTION TO ENGENEERING', 'Introduction to Engineering'), ('SPACE', 'Space'), ('ROBOTS', 'Robots'), ('NATURE', 'Nature'), ('MEDICINE', 'Medicine'), ('STRUCTURE', 'Structure'), ('CHEMISTRY', 'Chemistry'), ('ENERGY', 'Energy'), ('MATERIAL', 'Material'), ('LIGHTS', 'Lights')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('downloadable_resources', models.FileField(blank=True, null=True, upload_to='activities/resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
