# Generated by Django 5.1.4 on 2025-01-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_topics_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='category',
            new_name='topics',
        ),
    ]
