# Generated by Django 5.1.4 on 2025-01-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_category_topics_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='downloadable_resources',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics',
        ),
        migrations.AlterField(
            model_name='topics',
            name='title',
            field=models.CharField(choices=[('INTRODUCTION TO ENGENEERING', 'Introduction to Engineering'), ('SPACE', 'Space'), ('ROBOTS', 'Robots'), ('NATURE', 'Nature'), ('MEDICINE', 'Medicine'), ('STRUCTURE', 'Structure'), ('CHEMISTRY', 'Chemistry'), ('ENERGY', 'Energy'), ('MATERIAL', 'Material'), ('LIGHTS', 'Lights')], max_length=50),
        ),
    ]
