# Generated by Django 5.1.4 on 2024-12-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('JUNK_MODEL', 'Junk Modelling'), ('PHYSICAL', 'Physical Activities'), ('PLAY_PROVOCATION', 'Play Provocations'), ('WORKSHEETS', 'Worksheets & Games'), ('EXTENSIONS', 'Extensions')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('instructions', models.TextField()),
                ('preparation_time', models.PositiveIntegerField(blank=True, help_text='Time in minutes', null=True)),
                ('required_materials', models.TextField(blank=True, help_text='List of materials', null=True)),
                ('downloadable_resources', models.FileField(blank=True, null=True, upload_to='activities/resources/')),
                ('curriculum_links', models.TextField(blank=True, help_text='Curriculum alignment details', null=True)),
                ('engineering_skills', models.TextField(blank=True, help_text='List of skills developed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
