# Generated by Django 5.1.4 on 2024-12-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='engineering_skills',
        ),
    ]
